### ISSUE TITLE
Response code 403 (Forbidden) for all videos

### ISSUE THREAD

**Issue by rpungello** [Inrixia/Floatplane-Downloader#132] opened 2022-10-13 13:39 UTC
Seems since around 9/29 I've been unable to download videos from Floatplane, based on the fact that the last LTT video I have in my Plex library is the Dual ITX in one case from that day.

When I check the logs from the Docker container, it's just a bunch of 403 errors (shown below).
I have my Floatplane credentials set via docker-compose environment variables, and haven't changed anything in that regard.
Wondering if Floatplane changed something with regards to authentication. Is there a way to get more verbose logging out? I'd be curious to see which step it's failing on, authentication or download.

```
Linus Tech Tips - Microsoft vs S: ████████████████████████████████████████ 100% | ERR: Response code 403 (Forbidden) - Retrying 0/3
fp-downloader            | Linus Tech Tips - Linus and Jake: ████████████████████████████████████████ 100% | ERR: Response code 403 (Forbidden) - Retrying 0/3
fp-downloader            | ShortCircuit - SC: I've been wai: ████████████████████████████████████████ 100% | ERR: Response code 403 (Forbidden) - Retrying 0/3
fp-downloader            | Floatplane Exclusive - FP Exclus:                                            0% | 
fp-downloader            | ShortCircuit - SC: I've never be:                                            0% | 
fp-downloader            | .ShortCircuit - SC: I've been wa:                                            0% | 
fp-downloader            |                .Linus Tech Tips : ████████████████████████████████████████ 100% | ERR: Response code 403 (Forbidden) - Retrying 1/3
fp-downloader            |                ..Linus Tech Tips: ████████████████████████████████████████ 100% | ERR: Response code 403 (Forbidden) - Retrying 2/3
fp-downloader            |               ...Linus Tech Tips:                                            0% | 
```

**Comment by Inrixia** [comment] 2022-10-13 21:02
Pretty sure this is a duplicate of https://github.com/Inrixia/Floatplane-Downloader/issues/130

For now use the dev tag and it should be fixed

**Comment by rpungello** [comment] 2022-10-13 22:13
Alright, dev tag seems to be working. Thanks!

**Comment by Inrixia** [comment] 2022-10-13 22:20
Leaving this open till I get around to merging dev changes into a new release

**Closed** 2022-10-31 07:48 UTC
Labels: float api issue, awaiting fix confirmed
