### ISSUE TITLE
Unraid container stable branch failure

### ISSUE THREAD

**Issue by sthorley** [Inrixia/Floatplane-Downloader#210] opened 2024-09-25 19:08 UTC
I was installing the stable channel on unraid  (using the version from the app gallery) and received the same error users reported in [issue 197](https://github.com/Inrixia/Floatplane-Downloader/issues/197). 

Using the dev branch installed successfully so I'm assuming the stable build was not updated yet for unraid?

**Comment by Inrixia** [comment] 2024-09-26 05:16
The stable branch is identical to dev for this issue.

The problem is the but is with the base node image which won't update unless you force it to on your system. Pulling the dev image will result in using the latest base image.

Closing this for now. Updating the base image and pushing a new image for both branches should reduce the likely hood of this happening anyway.

But typically I try steer people to using the dev tag/branch anyway.

**Closed by Inrixia** 2024-09-26 05:17 UTC
