### ISSUE TITLE
ERR: spawn ./db/ffmpeg ENOENT

### ISSUE THREAD

**Issue by Catacas** [Inrixia/Floatplane-Downloader#100] opened 2021-11-03 08:45 UTC
Hi, I'm running the downlaoder in docker on Unraid.

Everytime there is a new Video, it does download the video, but can't process it. 
![image](https://user-images.githubusercontent.com/9129041/140030922-bf01f703-7c22-4810-b27d-0ef244e23045.png)
When I go into the download folder it looks like this.
![image](https://user-images.githubusercontent.com/9129041/140028988-460c9ae5-8b90-4590-b5ca-bdac36f0e75d.png)
My configuration looks like this.
![image](https://user-images.githubusercontent.com/9129041/140030764-48753280-7777-430d-908c-790ec1072068.png)

**Comment by Inrixia** [comment] 2021-11-03 08:46
What tag are you running for the docker version?

**Comment by Catacas** [comment] 2021-11-03 08:48
Currently non. Should I change it to latest?

**Comment by Inrixia** [comment] 2021-11-03 08:49
Yes please try latest

**Comment by Catacas** [comment] 2021-11-03 08:54
The log gives the same Error codes

**Comment by Inrixia** [comment] 2021-11-03 08:55
Can you check what exists under the db folder? ffmpeg should be saved there and should be executable

**Comment by Catacas** [comment] 2021-11-03 08:57
only a folder called "channels", cookies.json and settings.json

**Comment by Inrixia** [comment] 2021-11-03 08:58
Can you try running with headless set to false and let me know if that works better?

**Comment by Catacas** [comment] 2021-11-03 09:02
Yes! That worked. Now it said, that ffmpeg is missing and it downloaded it. The videos get processed aswell.
Thanks for the very quick response!

**Comment by Inrixia** [comment] 2021-11-03 09:04
This appears to be a remenant of https://github.com/Inrixia/Floatplane-Downloader/issues/82 caused by this https://github.com/Inrixia/Floatplane-Downloader/issues/57...

Ill need to fix this in the next release, leaving this issue open. For now use headless=false but understand it may result in behaviour not supported for a docker enviroment.

**Comment by Inrixia** [comment] 2021-11-03 09:09
Found the issue. https://github.com/Inrixia/Floatplane-Downloader/issues/57 does not update this line so when running headless ffmpeg is attempting to spawn from the wrong directory...

https://github.com/Inrixia/Floatplane-Downloader/blob/89338835bc6139811d391c09b6b7f71ae1a7a849/src/lib/Video.ts#L172

Should check for headless and set appropriately #todo

**Comment by Catacas** [comment] 2021-11-03 09:12
FYI I wouldn't run it with the headless in docker. The downloader works and processes the videos. But at the same time it crashed the whole UI of UNraid. When I stoped the downloader through putty the UI worked again.

**Comment by Inrixia** [comment] 2021-11-03 09:12
> FYI I wouldn't run it with the headless in docker. The downloader works and processes the videos. But at the same time it crashed the whole UI of UNraid. When I stoped the downloader through putty the UI worked again.

Do you mean wouldn't run it with headless true or headless false?

**Comment by Catacas** [comment] 2021-11-03 09:14
When I set headless to false the downloader worked, but th GUI of unriad crashed. When the downloader was stoped the GUI worked again.

**Comment by Inrixia** [comment] 2021-11-03 09:14
Right yea, probably due to the console spam. Ill push a fix for the headless ffmpeg issue for you to test soon

**Comment by Inrixia** [comment] 2021-11-03 09:30
> Found the issue. #57 does not...

Actually this is wrong was looking at the wrong branch. @Catacas Are you sure your using the latest version when headless=true was not working? Can you try with headless enabled now?

**Comment by Catacas** [comment] 2021-11-03 09:51
I've tried a few things. 
I stoped the container, delted everything in the db and video folder, set headless to true and started it again.
Then I got the error from the beginning again.
I stoped it again, set headless to false and started it again. Then all the videos were processed and the ui crashed. 
I stoped it again deleted everything except ffmpeg from the db and video folder, set headless to true and ran it again and it worked.

So it apperas, that in headless mode it doesn't check if ffmpeg exists or doesn't download it

**Comment by Inrixia** [comment] 2021-11-03 09:52
Mmk, Ill fix this now then

**Comment by Inrixia** [comment] 2021-11-03 09:56
Should be fixed in https://github.com/Inrixia/Floatplane-Downloader/commit/0f404e70ea44c13bd4ffda5f386b5bbe23634eaa

Please do a clean install with latest and see if its fixed @Catacas.

**Comment by Catacas** [comment] 2021-11-03 10:09
Now it said:
`Ffmpeg binary missing! Downloading... Done!`
But ffmpeg is not in the db folder, so I got the same error

**Comment by Inrixia** [comment] 2021-11-03 10:15
Ok, https://github.com/Inrixia/Floatplane-Downloader/commit/5b51b08e4ea94811461ef11aa1272595263d65a2 should properly fix this without breaking things now. Once https://github.com/Inrixia/Floatplane-Downloader/actions/runs/1416220216 finishes please do a clean install on latest again and see if its fixed running with `headless=true` thanks :)

**Comment by Catacas** [comment] 2021-11-03 10:43
Same error again. Would it be possible, that you print the current version at the beginning just to make sure, that I have the right version?

**Comment by Inrixia** [comment] 2021-11-03 10:54
If your pulling a new image then it will be up to date. That said I should probably add a version printout at some point.

Ive pushed some changes that might fix it. Please pull from docker hub and test.

**Comment by Catacas** [comment] 2021-11-03 11:02
Same error and still no ffmpeg.

**Comment by Inrixia** [comment] 2021-11-03 11:26
Pushed some changes, please try them out and let me know if it works.

Also if you can see the folder structure of the container not just the ./db folder that would be helpful.

**Comment by Catacas** [comment] 2021-11-03 11:36
Same error and no ffmpeg in the db folder. But there is ffmpeg in the root folder.

**Comment by Inrixia** [comment] 2021-11-03 11:36
Hmm, and the ffmpeg in the db folder has no file extension its just called ffmpeg?

**Comment by Catacas** [comment] 2021-11-03 11:40
inside the db folder there is no ffmpeg and in the root folder it is just ffmpeg with no file extensiton.
![image](https://user-images.githubusercontent.com/9129041/140053773-adf11921-f020-4d3e-9848-cc61b99dfc83.png)

**Comment by Catacas** [comment] 2021-11-03 11:40
sorry, not root but this is the fp folder

**Comment by Inrixia** [comment] 2021-11-03 11:41
Hmm, ok progress maybe. ffmpeg should be inside that folder.

Pull the latest and try now

**Comment by Catacas** [comment] 2021-11-03 11:54
still the same.

**Comment by Inrixia** [comment] 2021-11-03 11:55
Hmm this is beginning to look like some kinda weird permissions error.

**Comment by Inrixia** [comment] 2021-11-03 11:56
Go ahead and repull this one should fix it

**Comment by Catacas** [comment] 2021-11-03 12:06
i just noticed, that you are changing dev and not latest
![image](https://user-images.githubusercontent.com/9129041/140057005-a5fac63a-2ad8-4666-89b5-81e76c328329.png)
I was still on latest. I'm gonna try dev

**Comment by Inrixia** [comment] 2021-11-03 12:10
Go ahead and re-pull. Ive rolled back dev to how it was before the patches.

**Comment by Inrixia** [comment] 2021-11-03 12:10
I bet this was fixed in https://github.com/Inrixia/Floatplane-Downloader/issues/82 all along

**Comment by Catacas** [comment] 2021-11-03 12:17
wich one should i download? latest still has the issue

**Comment by Inrixia** [comment] 2021-11-03 12:17
Use dev

**Comment by Catacas** [comment] 2021-11-03 12:24
YES! That works!

**Comment by Inrixia** [comment] 2021-11-03 12:25
Hah so it was fixed all along and I was running in circles. Funny.

Closing as this is a duplicate of https://github.com/Inrixia/Floatplane-Downloader/issues/82

Let me know if you run into any other issues :)

**Comment by Catacas** [comment] 2021-11-03 12:26
Thank you very much!

**Closed by Inrixia** 2021-11-03 12:25 UTC
Labels: bug, awaiting fix confirmed, in progress
