### ISSUE TITLE
Request Error Causing Container to Stop

### ISSUE THREAD

**Issue by guitaristtom** [Inrixia/Floatplane-Downloader#106] opened 2021-11-28 09:40 UTC
Here is the error that I'm getting:

```
> Fetching latest videos from [Linus Tech Tips]... Fetched 0 videos! Skipped 0.
node:internal/process/promises:246
triggerUncaughtException(err, true /* fromPromise */);
^

RequestError: Timeout awaiting 'request' for 30000ms
at ClientRequest.<anonymous> (/fp/node_modules/got/dist/source/core/index.js:956:65)
at Object.onceWrapper (node:events:510:26)
at ClientRequest.emit (node:events:402:35)
at ClientRequest.origin.emit (/fp/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
at Socket.socketErrorListener (node:_http_client:447:9)
at Socket.emit (node:events:390:28)
at emitErrorNT (node:internal/streams/destroy:164:8)
at emitErrorCloseNT (node:internal/streams/destroy:129:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at Timeout.timeoutHandler [as _onTimeout] (/fp/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
at listOnTimeout (node:internal/timers:559:11)
at processTimers (node:internal/timers:500:7) {
name: 'TimeoutError',
code: 'ETIMEDOUT',
timings: {
start: 1638088686410,
socket: 1638088686410,
lookup: 1638088686411,
connect: 1638088686411,
secureConnect: undefined,
upload: 1638088686411,
response: undefined,
end: undefined,
error: 1638088716410,
abort: undefined,
phases: {
wait: 0,
dns: 1,
tcp: 0,
tls: undefined,
request: 0,
firstByte: undefined,
download: undefined,
total: 30000
}
},
event: 'request'
}
```

Right now, I have my container set to auto restart, but this still seems like something _that should be fixed_ somehow.

It's _kind of_ similar to #104.

**Comment by Inrixia** [comment] 2021-11-28 09:44
Ima close this since it's a duplicate of #104 please post any further comments or errors around this on that issue.

Not sure if this is a rare bug or a floatplane api issue. Could be a bit of both. Thanks for reporting it

**Closed by Inrixia** 2021-11-28 09:44 UTC
